[package]
name = "medicine-inventory-pos"
version = "0.1.0"
description = "MY MEDICAL offline pharmacy management desktop application"
edition = "2021"
rust-version = "1.90"

[lib]
name = "medicine_inventory_pos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
zip = { version = "2.4.2", default-features = false, features = ["deflate"] }
